<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda[
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, direccion, telefono, email, edad, estado_civil)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefeno (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT estado_civil (#PCDATA)>
]>
<agenda>
<contacto>
  <nombre>Pedro</nombre>
  <direccion>olmo</direccion>
  <telefono>123456789</telefono>
  <email>pedro@gmail.com</email>
  <edad>22</edad>
  <estado_civil>soltero</estado_civil>
</contacto>
</agenda>